Repository eclipse-ankaios/ank-sdk-python, pull requests merged in 2025-07, with the labels that each got.

#78 Add step to fail the job if check failed
  .github/workflows/build.yml
  ankaios_sdk/ankaios.py
  tests/test_ankaios.py
Labels: bug, ready for review, CI/CD

#83 Change priority of startup log message
  ankaios_sdk/_components/control_interface.py
Labels: ready for review, minor

#76 Add Workload Files Support
  ankaios_sdk/_components/__init__.py
  ankaios_sdk/_components/file.py
  ankaios_sdk/_components/workload.py
  ankaios_sdk/utils.py
  docs/source/file.rst
  docs/source/index.rst
  examples/README.md
  examples/apps/test_files.py
  setup.cfg
  tests/test_complete_state.py
  tests/workload/test_file.py
  tests/workload/test_workload.py
  tests/workload/test_workload_builder.py
Labels: enhancement, ready for review, blocked

#62 Support for workload log collection
  ankaios_sdk/_components/__init__.py
  ankaios_sdk/_components/control_interface.py
  ankaios_sdk/_components/file.py
  ankaios_sdk/_components/log_campaign.py
  ankaios_sdk/_components/request.py
  ankaios_sdk/_components/response.py
  ankaios_sdk/_components/workload.py
  ankaios_sdk/_components/workload_builder.py
  ankaios_sdk/_components/workload_state.py
  ankaios_sdk/ankaios.py
  docs/source/file.rst
  docs/source/index.rst
  docs/source/log_campaign.rst
  docs/source/response.rst
  docs/source/workload.rst
  docs/source/workload_builder.rst
  examples/README.md
  examples/apps/follow_state.py
  examples/apps/get_logs.py
  examples/apps/hello_ankaios.py
  examples/manifest.yaml
  examples/stop_example.sh
  setup.py
  tests/request/__init__.py
  tests/request/test_get_state_request.py
  tests/request/test_logs.py
  tests/request/test_request.py
  tests/request/test_update_state_request.py
  tests/response/test_log_response.py
  tests/response/test_response.py
  tests/test_ankaios.py
  tests/test_complete_state.py
  tests/test_control_interface.py
  tests/test_log_queue.py
  tests/test_workload_builder.py
  tests/workload/test_access_right_rule.py
  tests/workload/test_workload.py
  tests/workload_state/test_workload_instance_name.py
Labels: enhancement, ready for review
